
7 CONSTANT NUMBER-SIZE
50000 CONSTANT MAXIMUM-NUMBER
NUMBER-SIZE MAXIMUM-NUMBER * CONSTANT LINE-MAX-LENGTH
CREATE INPUT-LINE LINE-MAX-LENGTH ALLOT
VARIABLE MAX-NUMBER
CREATE NUMBERS MAXIMUM-NUMBER CELLS ALLOT

: READ-NUMBERS
    INPUT-LINE DUP LINE-MAX-LENGTH 
    STDIN READ-LINE THROW
    IF EVALUATE ELSE 2DROP THEN ;

: IS-DIGIT ( c -- f )
    DUP 48 >= SWAP 57 <= AND ;

: GET-NUMBER ( a -- a',n )
    BEGIN
        DUP C@ IS-DIGIT 0= WHILE 1+
    REPEAT
    0
    BEGIN 
        OVER C@ DUP IS-DIGIT WHILE
            48 - 
            SWAP 10 * +
            SWAP 1+ SWAP
    REPEAT
    DROP ;

: GET-NUMBERS ( a,m,n -- )
    0 DO                 \ a,m
        SWAP GET-NUMBER  \ m,a',x
        ROT DUP >R !     \ a' -- m <- x
        R> CELL+         \ a',m'
    LOOP 
    2DROP ;

: PRINT-NUMBERS ( m,n -- )
    0 DO
        DUP I CELLS + @ . 
    LOOP DROP ;

READ-NUMBERS MAX-NUMBER !
INPUT-LINE LINE-MAX-LENGTH STDIN READ-LINE THROW
2DROP .s 
INPUT-LINE NUMBERS MAX-NUMBER @ GET-NUMBERS
NUMBERS MAX-NUMBER @ PRINT-NUMBERS
CR BYE
